### ISSUE TITLE
Data loading very slow

### ISSUE THREAD

**Issue by LaoshuBaby** [yuiseki/osm-address-editor-vite#1]
Hello, yuiseki-san!

First of all I would like to appreciate you very much for creating this editor, it gives the mapper a view of what work has been done and it gives a sense of achievement when the avatar is displayed on the map.

However, I would like to ask you to speed the access of the site, it is difficult to load specific roads outside of Japan and it is difficult to know where visitors are trying to view. The buildings take a long time to load and sometimes only a few buildings are visible and only the progress circle is spinning all the time.

If you think this issue bothers you, or have no plans to fix it, you can simply close it without any explanation.

Again, I apologise for taking your time and making you read these complaints!

---

您好，yuiseki桑

首先我应当对您所创造的这个编辑器非常感谢，它令绘图者可以更清晰的认识到做出了哪些工作，并且当头像显示在地图上的时候将更具有成就感。

但我希望向您请求改进网站的访问速度，在日本以外的地方都很难加载出来具体的道路，很难知道所查看的试图位于何处。且建筑的加载时间很长，有时只能看到很少的几座建筑，只有进度条在旋转。

如果您觉得这份issue会令您感到困扰，或者没有计划修复它，您可以直接关闭掉它而不做任何解释。

再次为耗费您时间，让您阅读这些抱怨感到抱歉！

---

![图片](https://user-images.githubusercontent.com/42690037/157831459-4b291c01-f2e4-424b-97dc-9725eb17e682.png)

**Comment by yuiseki** [comment]
Thank you so much for report the Issue!
I have been developing this project alone, so it would be great to hear from you.


I think you are right that data loading was very slow,
because until yesterday this project was incomplete,
It was at the prototype level.

Today, I have made some improvements about data loading.
Take measures to avoid loading data too frequently,
and the amount of data to be loaded is now adjusted according to the zoom level of the map.
I hope this has improved things a bit.


It seems to be another problem with the map loading.
I am currently using map data provided free of charge by a Japanese company in this project.
Therefore, there may be some problem accessing from outside of Japan or displaying maps outside of Japan.

I hope this project will be interested and useful for OpenStreetMap mappers around the world,
and I would very much want to improve it so that people in any country can use it comfortably.
So I will investigate and take action with the map loading.


And I am sorry, but you may face another problem if you actually try to use this project for edit address.
The data structure of addresses in OpenStreetMap has no clear rules and quite different from country to country,
and this project only supports Japan yet.

I'm trying to figure out what I can do about this issue as well.

Until support another country can be made,
I would like you to go to the OpenStreetMap website and edit the building address.


Thanks for contacting me with interest in this project!

**Comment by LaoshuBaby** [comment]
> It seems to be another problem with the map loading.
> I am currently using map data provided free of charge by a Japanese company in this project.
> Therefore, there may be some problem accessing from outside of Japan or displaying maps outside of Japan.


I noticed this, and found attribuation of geoloniamaps in the right bottom of screen.
Maybe you can try mapbox? They offer some free quota for personal developer.



> And I am sorry, but you may face another problem if you actually try to use this project for edit address.
> The data structure of addresses in OpenStreetMap has no clear rules and quite different from country to country,
> and this project only supports Japan yet.

I also feel sorry for this……because I'm not a frontend developer. If those pattern can stored in some makeup language, it will allow mapper from other country write their own pattern.

(It is another kind of l10n, so I'm afraid this requeset will bring a havey burden to you)

**Comment by yuiseki** [comment]
Hi LaoshuBaby-san!
Thank you for kind reply.


I've figure out that vector tile map I've used does not support detailed zoom level outside of Japan.
So I decide to change the base map of this project to the OpenStreetMap official raster tile server.
Now this project is available to the whole world!
...At least as far as browsing who are last editor of building.


Also I've made more improvement about data loading.
If the zoom level is less than 16, maps does not load any data and just displays an icon asking for further zooming.


I will continue to look into the editing of the address in other country.
I've put that on a separate Issue #2 

Thank you for your concern.
I am on a mission with this project.
The more difficult the problem, the more motivated I am, and that's okay.


This issue is closed as resolved.
If you still have problems, please Reopen.


Once again, thanks so much for bringing to my attention that this map wasn't working outside of Japan!


P.S.
I could find you near Beijing station using this map...!
I have great respect for OpenStreetMap mappers.
I am honored to have been so kindly contacted by one of the mapper I so respect.
https://yuiseki.github.io/osm-address-editor-vite/#17.44/39.904563/116.419165
[![Image from Gyazo](https://i.gyazo.com/fe689bab7d934ffbbf49345897aa8d4a.png)](https://gyazo.com/fe689bab7d934ffbbf49345897aa8d4a)
